{{- if .Values.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deployments-service
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deployments-service
                port:
                  number: {{ .Values.server.port }}
{{- end }}
