apiVersion: v1
kind: Secret
metadata:
  name: deployments-service-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_ADMIN_URL: {{ printf "postgres://postgres:%s@%s:%v/%s" (.Values.secrets.dbAdminPassword | urlquery) .Values.db.host .Values.db.port .Values.db.name | quote }}
  REDIS_URL: {{ printf "redis://:%s@%s:%v/%v" (.Values.secrets.redisPassword | urlquery) .Values.redis.host .Values.redis.port .Values.redis.db | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GH_WEBHOOK_SECRET: {{ .Values.secrets.ghWebhookSecret | quote }}
